ALTER TABLE "Payment"
ADD COLUMN IF NOT EXISTS "refundedAmount" INTEGER NOT NULL DEFAULT 0;

ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'REFUNDED_PARTIAL';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BILLING_REFUND_ISSUED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BILLING_CANCEL_IMMEDIATE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BILLING_CANCEL_SCHEDULED';
